### ISSUE TITLE
Buffer adjustment for sources results in incorrect dims when buffer > 0

### ISSUE THREAD

**Issue by joncjones** [Circuitscape/Omniscape.jl#53] opened 2020-07-24 14:57 UTC
Hello all - Can you please advise me on this - I am trying to run a test with Omniscape and it starts normally but then crashes with the following error:

```julia
signal (11): Segmentation fault
in expression starting at none:0
in expression starting at none:0
in expression starting at none:0
in expression starting at none:0
in expression starting at none:0
```

I am running the latest version of Omniscape (downloaded today) with Julia 1.4.2 on a Unix machine  [High Performance Cluster](https://arc.leeds.ac.uk/systems/arc4/).

The files I am using are here:
[RUN6.zip](https://github.com/Circuitscape/Omniscape.jl/files/4972661/RUN6.zip)

run6.ini - is config file 
run6-output.txt - output of the run up until crash
PAC6510K.tif - is the raster and assrtd files

Any advice greatly appreciated ! 

J

**Comment by vlandau** [comment] 2020-07-24 16:26
Sure happy to take a look. Was there a stacktrace preceding or following that error message? If so can you append it to your initial message? Thanks!

**Comment by joncjones** [comment] 2020-07-24 16:33
Great thanks!  There was nothing else - I put everything that was thrown out by the HPC (as .e or .o files) into run6-output.txt (see above).

**Comment by vlandau** [comment] 2020-07-24 17:12
For my and other devs' reference, here's the full stacktrace extracted from the output text file. Pretty sure it's out of order, I'll rearrange if/when I figure it out
```julia
ERROR:
LoadError: 
TaskFailedException:
DimensionMismatch("arrays could not be broadcast to a common size; got a dimension with lengths 23 and 24")
Stacktrace:
 [1] _bcs1 at ./broadcast.jl:490 [inlined]
 [2] _bcs at ./broadcast.jl:484 [inlined] (repeats 2 times)
 [3] broadcast_shape at ./broadcast.jl:478 [inlined]
 [4] combine_axes at ./broadcast.jl:473 [inlined]
 [5] instantiate at ./broadcast.jl:256 [inlined]
 [6] materialize at ./broadcast.jl:820 [inlined]
 [7] solve_target!(::Int64, ::Int64, ::Dict{String,Int64}, ::Array{Float64,2}, ::Array{Float64,2}, ::Array{Float64,2}, ::Dict{String,String}, ::Circuitscape.OutputFlags, ::Bool, ::Bool, ::Bool, ::Array{Float64,2}, ::Array{Float64,2}, ::Array{Float64,2}, ::Array{Float64,2}, ::String, ::String, ::Float64, ::Float64, ::Float64, ::Float64, ::Array{Float64,2}, ::Array{Float64,3}, ::Array{Float64,3}, ::DataType) at /home/home02/engjca/.julia/packages/Omniscape/ZVGgl/src/functions.jl:549
 [8] macro expansion at /home/home02/engjca/.julia/packages/Omniscape/ZVGgl/src/run_omniscape.jl:270 [inlined]
 [9] (::Omniscape.var"#78#threadsfor_fun#9"{Dict{String,Int64},DataType,Bool,Bool,Bool,String,String,Float64,Float64,Float64,Float64,Dict{String,String},Array{Float64,2},Int64,Circuitscape.OutputFlags,Int64,UnitRange{Int64}})(::Bool) at ./threadingconstructs.jl:61
 [10] (::Omniscape.var"#78#threadsfor_fun#9"{Dict{String,Int64},DataType,Bool,Bool,Bool,String,String,Float64,Float64,Float64,Float64,Dict{String,String},Array{Float64,2},Int64,Circuitscape.OutputFlags,Int64,UnitRange{Int64}})() at ./threadingconstructs.jl:28[ Info: 

Stacktrace:
 [1] wait(::Task) at ./task.jl:267
 [2] macro expansion at ./threadingconstructs.jl:69 [inlined]
 [3] run_omniscape(::String) at /home/home02/engjca/.julia/packages/Omniscape/ZVGgl/src/run_omniscape.jl:265
 [4] top-level scope at /home/home02/engjca/run_trial.jl:7
 [5] include(::Module, ::String) at ./Base.jl:377
 [6] exec_options(::Base.JLOptions) at ./client.jl:288
 [7] _start() at ./client.jl:484
in expression starting at /home/home02/engjca/run_trial.jl:7
signal (11): Segmentation fault
in expression starting at none:0
in expression starting at none:0
in expression starting at none:0
in expression starting at none:0
in expression starting at none:0

signal (11): Segmentation fault
in expression starting at none:0
```

**Comment by vlandau** [comment] 2020-07-24 17:32
Good news, I'm able to reproduce on my local machine so I'll get this fixed. It looks like this results from having a buffer specified in the ini. This feature (an additional buffer added to each moving window) is not essential or particularly useful, so for now, it you remove the buffer argument from your ini it should work for you. 

Stacktrace from my local machine:
```julia
ERROR: TaskFailedException:
DimensionMismatch("arrays could not be broadcast to a common size; got a dimension with lengths 23 and 24")
Stacktrace:
 [1] _bcs1 at ./broadcast.jl:490 [inlined]
 [2] _bcs at ./broadcast.jl:484 [inlined] (repeats 2 times)
 [3] broadcast_shape at ./broadcast.jl:478 [inlined]
 [4] combine_axes at ./broadcast.jl:473 [inlined]
 [5] instantiate at ./broadcast.jl:256 [inlined]
 [6] materialize at ./broadcast.jl:820 [inlined]
 [7] solve_target!(::Int64, ::Int64, ::Dict{String,Int64}, ::Array{Float64,2}, ::Array{Float64,2}, ::Array{Float64,2}, ::Dict{String,String}, ::Circuitscape.OutputFlags, ::Bool, ::Bool, ::Bool, ::Array{Float64,2}, ::Array{Float64,2}, ::Array{Float64,2}, ::Array{Float64,2}, ::String, ::String, ::Float64, ::Float64, ::Float64, ::Float64, ::Array{Float64,2}, ::Array{Float64,3}, ::Array{Float64,3}, ::DataType) at /root/.julia/packages/Omniscape/ZVGgl/src/functions.jl:549
 [8] macro expansion at /root/.julia/packages/Omniscape/ZVGgl/src/run_omniscape.jl:270 [inlined]
 [9] (::Omniscape.var"#78#threadsfor_fun#9"{Dict{String,Int64},DataType,Bool,Bool,Bool,String,String,Float64,Float64,Float64,Float64,Dict{String,String},Array{Float64,2},Int64,Circuitscape.OutputFlags,Int64,UnitRange{Int64}})(::Bool) at ./threadingconstructs.jl:61
 [10] (::Omniscape.var"#78#threadsfor_fun#9"{Dict{String,Int64},DataType,Bool,Bool,Bool,String,String,Float64,Float64,Float64,Float64,Dict{String,String},Array{Float64,2},Int64,Circuitscape.OutputFlags,Int64,UnitRange{Int64}})() at ./threadingconstructs.jl:28
Stacktrace:
 [1] wait(::Task) at ./task.jl:267
 [2] macro expansion at ./threadingconstructs.jl:69 [inlined]
 [3] run_omniscape(::String) at /root/.julia/packages/Omniscape/ZVGgl/src/run_omniscape.jl:265
 [4] top-level scope at REPL[6]:1
```

**Comment by joncjones** [comment] 2020-07-24 18:19
Ok that sounds promising - I will comment that out. I think I just grabbed a .ini from the test folder (config7.ini I think) and edited that so it must have been preset.

I will run it again and let you know what happens.  

Thanks !

**Comment by joncjones** [comment] 2020-07-24 18:49
Seems to complete the test fine now - well done and thanks for the speedy response !

**Comment by vlandau** [comment] 2020-07-24 18:51
Excellent! I've got a fix in the works for the buffer issue. There should be a patch release for Omniscape today that fixes it -- just double checking test results, etc. Thanks for identifying this bug!

I'll close the issue once I successfully merge the fix.

**Closed** 2020-07-24 20:00 UTC
Labels: bug
